#!/usr/bin/perl
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

my @templates = (qw(
                /etc/hosts
));

event_templates($_, @templates) foreach (qw(
    nethserver-hosts-update
    host-create 
    host-delete 
    host-modify 
));

event_actions('nethserver-hosts-update', qw(
	      initialize-default-databases 00
));

event_actions('migration-import', 'nethserver-hosts-migrate' => 50);

event_templates('nethserver-hosts-save', qw(
    /etc/resolv.conf
));

safe_symlink('/bin/true', 'root/etc/e-smith/validators/host-delete/S10placeholder');
safe_symlink('../actions/fwobject-referenced', 'root/etc/e-smith/validators/host-delete/S20fwobject-reference');
