#!/usr/bin/perl

use strict;
use esmith::Build::CreateLinks  qw(:all);

event_templates('nethserver-hosts-update', qw(
                /etc/hosts
));

event_actions('nethserver-hosts-update', qw(
	      initialize-default-databases 00
));


