#!/usr/bin/perl -wT
# vim: set ft=xml:

#----------------------------------------------------------------------
# heading     : Configuration
# description : Hostnames and addresses
# navigation  : 6000 6500
#----------------------------------------------------------------------
#----------------------------------------------------------------------
# copyright (C) 2002 Mitel Networks Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#
# Technical support for this program is available from Mitel Networks
# Please visit our web site www.mitel.com/sme/ for details.
#----------------------------------------------------------------------

use strict;
use esmith::FormMagick::Panel::hostentries;
my $fm = esmith::FormMagick::Panel::hostentries->new();
$fm->display();

=begin testing

use esmith::FormMagick::Tester;
use esmith::TestUtils;
use esmith::TestUtils;
use esmith::ConfigDB;
use esmith::AccountsDB;

my $panel = $Original_File;
my $ua = esmith::FormMagick::Tester->new();

my $c = esmith::ConfigDB->open();
my $a = esmith::AccountsDB->open();

is  (mode($panel), '4750',              "Check permissions on script");
ok  ($ua->get_panel($panel),            "ABOUT TO RUN L10N TESTS");
is  ($ua->{status}, 200,                "200 OK");
#like($ua->{content}, qr/FORM_TITLE/,    "Saw untranslated form title");
ok  ($ua->set_language("en-us"),        "Set language to U.S. English");
ok  ($ua->get_panel($panel),            "Get panel");
is  ($ua->{status}, 200,                "200 OK");
like($ua->{content}, qr/Hostnames and addresses/, "Saw translated form title");

ok  ($ua->get_panel($panel),            "ABOUT TO TEST CREATING HOST");
ok  ($ua->follow("Click here"),         "Follow 'create host' link");
is  ($ua->{status}, 200,                "200 OK");
like($ua->{content}, qr/Create\/modify host/,   "Saw page
title");
like($ua->{content}, qr/Publish globally/,    "Saw fields");
like($ua->{content}, qr/Next/,    "Saw next button");

ok  ($ua->get_panel($panel),            "ABOUT TO TEST MODIFYING HOST");
ok  ($ua->follow("Modify"),         "Follow 'modify' link");
is  ($ua->{status}, 200,                "200 OK");

ok  ($ua->get_panel($panel),            "ABOUT TO TEST REMOVING HOST");
ok  ($ua->follow("Remove"),         "Follow 'remove' link");
is  ($ua->{status}, 200,                "200 OK");


=end testing

=cut


__DATA__
<form title="Hostnames and addresses" header="/etc/e-smith/web/common/head.tmpl"
    footer="/etc/e-smith/web/common/foot.tmpl">
    <page name="First" pre-event="print_status_message()">
        <subroutine src="print_hosts_tables()" />
    </page>
    <page name="CreateModify" pre-event="turn_off_buttons()" post-event="more_options()">
        <title>CREATE_TITLE</title>
        <subroutine src="print_hostname_field()" />
        <subroutine src="print_domain_field()" />
        <field  
            type="text" size="30"
            id="comment" >
            <label>COMMENT</label>
        </field> 
        <field type="select" 
            id="hosttype" 
            options="'Self' => 'SELF', 'Local' => 'LOCAL', 'Remote' => 'REMOTE'" 
            value='Self'>
            <label>LOCATION</label>
        </field>
        <subroutine src="print_button('NEXT')" />
    </page>
    <page name="Remove" pre-event="turn_off_buttons()" post-event="remove()">
        <description>REMOVE_PAGE_DESCRIPTION</description>
        <subroutine src="print_button('REMOVE')" />

    </page>
    <page name="Local" pre-event="turn_off_buttons()"
        post-event="goto_confirm()">
        <description>LOCAL_PAGE_DESCRIPTION</description>
        <field type="text" id="local_ip"
            validation="ip_number, not_in_dhcp_range, not_taken, must_be_local">
            <label>LOCAL_IP</label>
            <description>LOCAL_IP_DESCRIPTION</description>
        </field>
        <field type="text" id="ethernet_address"
            validation="mac_address_or_blank">
            <label>ETHERNET_ADDRESS</label>
            <description>ETHERNET_ADDRESS_DESCRIPTION</description>
        </field>
        <subroutine src="print_button('NEXT')" />
    </page>
    <page name="Remote" pre-event="turn_off_buttons()" post-event="goto_confirm()">
        <description>REMOTE_PAGE_DESCRIPTION</description>
        <field type="text" id="global_ip">
            <label>IP_ADDRESS</label>
        </field>
        <subroutine src="print_button('NEXT')" />
    </page>

    <page name="Confirm" pre-event="turn_off_buttons()"
        post-event="create_or_modify()">
        <description>CONFIRM_DESCRIPTION</description>
        <subroutine src="print_confirmation_details('FINISH')" />
        <subroutine src="print_save_or_add_button()" />
    </page>
</form>
